7 manifestsetup
Secur1ty-21/practicum-android-diploma pull request #11
Opened 2024-02-17 17:57 UTC by VictorBlyakherov

Ориентация экрана
 Ссылка на класс Application
 Использование темы указанной в тз
 Добавление иконки приложения 
 добавить доступ к интернету

2024-02-17 19:22 UTC, Secur1ty-21 requested changes

2024-02-17 19:22 UTC, Secur1ty-21 commented on app/src/main/AndroidManifest.xml
> +        android:theme="@style/Theme.MaterialComponents.DayNight.NoActionBar"
Думаю это может сломать логику theming приложения, те атрибуты цветов которые мы будем применять в теме PracticumAndroidDiploma  могут перестать работать

2024-02-17 19:30 UTC, PavelKhomenko commented on app/src/main/AndroidManifest.xml
> +        android:theme="@style/Theme.MaterialComponents.DayNight.NoActionBar"
ну да, мы же в стиле наследуемся от parent="Theme.Material3.DayNight.NoActionBar" этого должно хватать

2024-02-17 19:35 UTC, PavelKhomenko commented on app/src/main/AndroidManifest.xml
> -        android:roundIcon="@mipmap/ic_launcher_round"
думаю, что стоит вернуть эту строчку, для отображения круглой иконки)

2024-02-17 19:36 UTC, Secur1ty-21 commented on app/src/main/AndroidManifest.xml
> +        android:theme="@style/Theme.MaterialComponents.DayNight.NoActionBar"
По заданию надо наследовать от Theme.MaterialComponents.DayNight.NoActionBar, но это нужно сделать в файлах тем а не в манифесте
![image](https://github.com/Secur1ty-21/practicum-android-diploma/assets/72816249/f2d8cf97-8c3a-46de-b951-b710e62497fc)

2024-02-17 19:38 UTC, PavelKhomenko commented on app/src/main/AndroidManifest.xml
> +        android:theme="@style/Theme.MaterialComponents.DayNight.NoActionBar"
ну я про это и написал, получается, что нужно вернуть 
android:theme="@style/Theme.PracticumAndroidDiploma"

2024-02-17 22:57 UTC, VictorBlyakherov commented on app/src/main/AndroidManifest.xml
> -        android:roundIcon="@mipmap/ic_launcher_round"
Нет, мне кажется, не нужно, если мы не делаем только Legacy иконку то она бывает только квадратной. Круглую система делает сама.

2024-02-17 23:01 UTC, VictorBlyakherov commented on app/src/main/AndroidManifest.xml
> +        android:theme="@style/Theme.MaterialComponents.DayNight.NoActionBar"
Исправлено

2024-02-18 22:58 UTC, Secur1ty-21 approved these changes

2024-02-18 23:11 UTC, merged