Team screen
Secur1ty-21/practicum-android-diploma pull request #38
Opened 2024-02-19 20:41 UTC by VictorBlyakherov

2024-02-19 22:34 UTC, Secur1ty-21 requested changes

2024-02-19 22:34 UTC, Secur1ty-21 commented on app/src/main/res/layout/fragment_team.xml
1.Думаю стоит отформатировать файл ctrl + alt + L
2. Скорее всего на этом экране более читаемо будет выглядеть LinearLayout

2024-02-19 22:34 UTC, Secur1ty-21 commented on app/src/main/res/layout/fragment_team.xml
> +    android:fontFamily="@font/ys_display_bold"
В дизайне указан ys_display_medium

2024-02-19 22:34 UTC, Secur1ty-21 commented on app/src/main/res/layout/fragment_team.xml
> +    android:layout_marginTop="@dimen/padding_24dp"
Вместе с padding получается отступ от top 32dp в дизайне 20dp ( Если не использовать toolbar то нужно смотреть расстояния до статус бара )

2024-02-19 22:34 UTC, Secur1ty-21 commented on app/src/main/res/layout/fragment_team.xml
> +        android:layout_marginTop="@dimen/padding_16dp"
Возможно стоит для улучшения читаемости  сделать просто marginTop=24dp

2024-02-19 22:34 UTC, Secur1ty-21 commented on app/src/main/res/values-night/styles.xml
> +        <item name="android:background">@color/yp_black</item>
Думаю будет лучше использовать другие способы смены цветов в зависимости от темы, если делать через styles происходит дублирование кода

2024-02-19 22:34 UTC, Secur1ty-21 commented on app/src/main/res/layout/fragment_team.xml
> +        android:fontFamily="@font/ys_display_medium"
Думаю стоит вынести в style textSize и fontFamily

2024-02-19 22:34 UTC, Secur1ty-21 commented on app/src/main/res/values/styles.xml
> +        <item name="android:textColor">@color/yp_black</item>
Скорее всего не продублировал пару параметров с ночного styles

2024-02-20 08:31 UTC, PavelKhomenko commented on app/src/main/res/layout/fragment_team.xml
> +    android:paddingStart="@dimen/padding_16dp"
кажется, что можно было использовать: <dimen name="border_margin">16dp</dimen>

2024-02-20 08:32 UTC, PavelKhomenko commented on app/src/main/res/layout/fragment_team.xml
> +    android:paddingStart="@dimen/padding_16dp"
ну и вообще удобнее делать через создание Guideline

2024-02-20 14:10 UTC, merged